In [ ]:
import numpy as np
import pandas as pd

# Task 0
Read the dataset from csv file & perform data cleaning - remove all rows, which contains `?` in some columns.
Also check for data correctness (salary & salary $K).

In [20]:
# write your code for task 0 here
df = pd.read_csv("../data/adult.csv")
df = df.replace("?", pd.NA)
df = df.dropna()
print(df["salary K$"].min(), df["salary K$"].max())
print(df["salary"].unique())
mask_incorrect = (
    ((df['salary'] == '<=50K') & (df['salary K$'] > 50)) |
    ((df['salary'] == '>50K') & (df['salary K$'] <= 50))
)

if mask_incorrect.any():
    print("Incorrect lines:")
    print(df[mask_incorrect])
else:
    print("All lines are correct salary and salary K$")

15 349
['<=50K' '>50K']
All lines are correct salary and salary K$

# Task 1
Print the count of men and women in the dataset.

In [46]:
# write your code for task 1 here
counts = df["sex"].value_counts()
print(counts)
counts_race = df["race"].value_counts()
print(counts_race)

sex
Male      20380
Female     9782
Name: count, dtype: int64
race
White                 25933
Black                  2817
Asian-Pac-Islander      895
Amer-Indian-Eskimo      286
Other                   231
Name: count, dtype: int64

# Task 2
Find the average age of men in dataset

In [22]:
# write your code for task 2 here
df[df["sex"]== "Male"]["age"].mean()

39.18400392541707

# Task 3
Get the percentage of people from Poland (native-country)

In [44]:
# write your code for task 3 here
percentage_poland = (df["native-country"] == "Poland").mean() * 100
print(f"Percentage of Poland is {round(percentage_poland, 3)} %")

Percentage of Poland is 0.186 %

# Task 4
Get the mean and standard deviation of the age for people who earn > 50K per year. After this, get it for those who earn <= 50K.

In [41]:
# write your code for task 4 here
df.groupby("salary")["age"].agg(["mean", "std"])

            mean        std
salary
<=50K   36.60806  13.464631
>50K    43.95911  10.269633

# Task 5
Check, if there are some people without higher education (education: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate), but with > 50K salary

In [51]:
# write your code for task 5 here
high_educ = [
    "Bachelors",
    "Prof-school",
    "Assoc-acdm",
    "Assoc-voc",
    "Masters",
    "Doctorate"
]
no_high_educ = df[(~df["education"].isin(high_educ)) & (df["salary"] == ">50K")]
print(no_high_educ)

       Unnamed: 0  age         workclass     education      marital-status  \
7               7   52  Self-emp-not-inc       HS-grad  Married-civ-spouse
10             10   37           Private  Some-college  Married-civ-spouse
55             55   43           Private  Some-college  Married-civ-spouse
67             67   53           Private       HS-grad  Married-civ-spouse
68             68   49      Self-emp-inc  Some-college  Married-civ-spouse
...           ...  ...               ...           ...                 ...
32462       32462   48      Self-emp-inc       HS-grad  Married-civ-spouse
32518       32518   57         Local-gov       HS-grad  Married-civ-spouse
32519       32519   46           Private  Some-college  Married-civ-spouse
32557       32557   40           Private       HS-grad  Married-civ-spouse
32560       32560   52      Self-emp-inc       HS-grad  Married-civ-spouse

              occupation relationship   race     sex  hours-per-week  \
7        Exec-managerial      Husband  White    Male              45
10       Exec-managerial      Husband  Black    Male              80
55          Tech-support      Husband  White    Male              40
67          Adm-clerical         Wife  White  Female              40
68       Exec-managerial      Husband  White    Male              50
...                  ...          ...    ...     ...             ...
32462       Craft-repair      Husband  White    Male              50
32518       Craft-repair      Husband  White    Male              40
32519    Exec-managerial      Husband  White    Male              48
32557  Machine-op-inspct      Husband  White    Male              40
32560    Exec-managerial         Wife  White  Female              40

      native-country salary  salary K$
7      United-States   >50K        307
10     United-States   >50K        116
55     United-States   >50K        341
67     United-States   >50K        225
68     United-States   >50K        194
...              ...    ...        ...
32462  United-States   >50K        343
32518  United-States   >50K        116
32519  United-States   >50K        239
32557  United-States   >50K        173
32560  United-States   >50K        243

[3178 rows x 13 columns]

# Task 6
Get the statistics of age for each type of education. Use `groupby` and `describe` for this.

In [52]:
# write your code for task 6 here
df.groupby("education")["age"].describe()

               count       mean        std   min   25%   50%   75%   max
education
10th           820.0  37.897561  16.225795  17.0  23.0  36.0  52.0  90.0
11th          1048.0  32.363550  15.089307  17.0  18.0  28.5  43.0  90.0
12th           377.0  32.013263  14.373710  17.0  19.0  28.0  41.0  79.0
1st-4th        151.0  44.622517  14.929051  19.0  33.0  44.0  56.0  81.0
5th-6th        288.0  41.649306  14.754622  17.0  28.0  41.0  53.0  82.0
7th-8th        557.0  47.631957  15.737479  17.0  34.0  49.0  60.0  90.0
9th            455.0  40.303297  15.335754  17.0  28.0  38.0  53.0  90.0
Assoc-acdm    1008.0  37.286706  10.509755  19.0  29.0  36.0  44.0  90.0
Assoc-voc     1307.0  38.246366  11.181253  19.0  30.0  37.0  45.0  84.0
Bachelors     5044.0  38.641554  11.577566  19.0  29.0  37.0  46.0  90.0
Doctorate      375.0  47.130667  11.471727  24.0  39.0  47.0  54.0  80.0
HS-grad       9840.0  38.640955  13.067730  17.0  28.0  37.0  48.0  90.0
Masters       1627.0  43.740012  10.735356  18.0  36.0  43.0  50.0  90.0
Preschool       45.0  41.288889  15.175672  19.0  30.0  40.0  53.0  75.0
Prof-school    542.0  44.249077  11.428098  25.0  36.0  43.0  50.0  90.0
Some-college  6678.0  36.135370  13.073528  17.0  25.0  35.0  45.0  90.0

# Task 7
Compare the married and non-married men salaries. Who earns more? (>50K or <=50K)
Married men are those, whom `marital-status` starts with "Married". Others are not.

In [61]:
# write your code for task 7 here
men = df[df["sex"] == "Male"]

married = ["Married-civ-spouse", "Married-AF-spouse", "Married-spouse-absent"]

married_men = men[men["marital-status"].isin(married)]
not_married_men = men[~men["marital-status"].isin(married)]

print("Married men average salary:")
print(married_men.groupby("salary")["salary K$"].mean())

print("\nNot married men average salary:")
print(not_married_men.groupby("salary")["salary K$"].mean())

Married men average salary:
salary
<=50K     31.927538
>50K     200.609820
Name: salary K$, dtype: float64

Not married men average salary:
salary
<=50K     32.091316
>50K     196.010401
Name: salary K$, dtype: float64

# Task 8
Get the max hours per week some person works. How many people works the same amount of hours per week?

In [67]:
# write your code for task 8 here
max_hours = df["hours-per-week"].max()
num_person_max = (df["hours-per-week"] == max_hours).sum()
print(f"Max hours per week: {max_hours}")
print(f"Number of people working {max_hours} hours per week: {num_person_max}")

Max hours per week: 99
Number of people working 99 hours per week: 78

# Task 9
Analyze the correlation between data in dataset. Understand connected fields in it and print highlight thier connection.

In [68]:
# write your code for task 9 here
numeric_cols = ["age", "hours-per-week", "salary K$"]
corr_matrix = df[numeric_cols].corr()
print(corr_matrix)

                     age  hours-per-week  salary K$
age             1.000000        0.101599   0.208203
hours-per-week  0.101599        1.000000   0.196378
salary K$       0.208203        0.196378   1.000000